version: "3"

vars:
  BINARY: geo
  BIN_DIR: .bin
  DATA_DIR: .data
  MODULE: github.com/joeblew999/plat-geo

includes:
  huma:
    taskfile: taskfiles/huma.yml
    optional: true
  restish:
    taskfile: taskfiles/restish.yml
    optional: true
  duckdb:
    taskfile: taskfiles/duckdb.yml
    optional: true
  nornicdb:
    taskfile: taskfiles/nornicdb.yml
    optional: true
  pmtiles:
    taskfile: taskfiles/pmtiles.yml
    optional: true
  tippecanoe:
    taskfile: taskfiles/tippecanoe.yml
    optional: true
  service:
    taskfile: taskfiles/service.yml
    optional: true
  src:
    taskfile: taskfiles/src.yml
    optional: true

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  dev:
    desc: Run dev server with hot reload
    cmds:
      - air

  build:
    desc: Build the binary
    deps: [huma:gen]
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/{{.BINARY}} ./cmd/{{.BINARY}}

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - goimports -w .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}} .tmp
      - rm -f coverage.out coverage.html openapi.json openapi.yaml

  install:
    desc: Install binary from manifest
    cmds:
      - xplat manifest install --force
