apiVersion: xplat/v1
kind: Package

name: plat-geo
version: dev
description: Geographical system for maps and routing with GeoParquet and PMTiles support
author: joeblew999
license: MIT

# Binary distribution
binary:
  name: geo
  source:
    # Primary: build from source if Go is available
    go: github.com/joeblew999/plat-geo/cmd/geo
    # Fallback: download from GitHub releases
    github:
      repo: joeblew999/plat-geo
      asset: geo-{{.OS}}-{{.ARCH}}

# Taskfile remote include configuration (for consumers)
taskfile:
  path: taskfiles/service.yml
  namespace: geo

# Process configuration for the geo server
processes:
  default:
    command: geo serve
    port: 8086
    health_path: /health
    readiness:
      initial_delay: 3
      period: 5

# Environment variables
env:
  required:
    - name: GEO_DATA_DIR
      description: Directory containing GeoParquet and PMTiles data files
  optional:
    - name: GEO_PORT
      description: Port for the geo server
      default: "8086"
    - name: GEO_HOST
      description: Host address to bind
      default: "0.0.0.0"
    - name: GEO_LOG_LEVEL
      description: Logging level (debug, info, warn, error)
      default: "info"

# Dependencies
dependencies:
  build:
    - go
  runtime: []

# Gitignore patterns
gitignore:
  patterns:
    - .bin/
    - .data/
    - "*.pmtiles"
    - "*.parquet"
