// Code generated by go run ./internal/gen/signals; DO NOT EDIT.

package editor

import (
	"github.com/joeblew999/plat-geo/internal/service"
)

// --- LayerConfig Signal Helpers ---

// LayerConfigSignalNames contains all Datastar signal names for LayerConfig.
// Use these constants in HTML templates: data-bind:{{LayerConfigSignalNames.Name}}
var LayerConfigSignalNames = struct {
	Name           string
	File           string
	PMTilesLayer   string
	GeomType       string
	DefaultVisible string
	Fill           string
	Stroke         string
	Opacity        string
}{
	Name:           "newlayername",
	File:           "newlayerfile",
	PMTilesLayer:   "newlayerpmtileslayer",
	GeomType:       "newlayergeomtype",
	DefaultVisible: "newlayervisible",
	Fill:           "newlayerfill",
	Stroke:         "newlayerstroke",
	Opacity:        "newlayeropacity",
}

// ParseLayerConfigSignals extracts a LayerConfig from Datastar signals.
func ParseLayerConfigSignals(s Signals) service.LayerConfig {
	return service.LayerConfig{
		Name:           s.String("newlayername"),
		File:           s.String("newlayerfile"),
		PMTilesLayer:   s.String("newlayerpmtileslayer"),
		GeomType:       s.String("newlayergeomtype"),
		DefaultVisible: s.Bool("newlayervisible"),
		Fill:           s.String("newlayerfill"),
		Stroke:         s.String("newlayerstroke"),
		Opacity:        s.Float("newlayeropacity"),
	}
}

// ResetLayerConfigSignals returns signals to reset the LayerConfig form.
func ResetLayerConfigSignals() map[string]any {
	return map[string]any{
		"newlayername":         "",
		"newlayerfile":         "",
		"newlayerpmtileslayer": "default",
		"newlayergeomtype":     "polygon",
		"newlayervisible":      true,
		"newlayerfill":         "#3388ff",
		"newlayerstroke":       "#2266cc",
		"newlayeropacity":      0.7,
	}
}
