// Code generated by go run ./cmd/humastargen; DO NOT EDIT.

package editor

import (
	"github.com/joeblew999/plat-geo/internal/humastar"
	"github.com/joeblew999/plat-geo/internal/service"
)

var LayerConfigSignalNames = struct {
	Name           string
	File           string
	PMTilesLayer   string
	GeomType       string
	DefaultVisible string
	Fill           string
	Stroke         string
	Opacity        string
	Published      string
}{
	Name:           "newlayername",
	File:           "newlayerfile",
	PMTilesLayer:   "newlayerpmtileslayer",
	GeomType:       "newlayergeomtype",
	DefaultVisible: "newlayervisible",
	Fill:           "newlayerfill",
	Stroke:         "newlayerstroke",
	Opacity:        "newlayeropacity",
	Published:      "newlayerpublished",
}

func ParseLayerConfigSignals(s humastar.Signals) service.LayerConfig {
	return service.LayerConfig{
		Name:           s.String("newlayername"),
		File:           s.String("newlayerfile"),
		PMTilesLayer:   s.String("newlayerpmtileslayer"),
		GeomType:       s.String("newlayergeomtype"),
		DefaultVisible: s.Bool("newlayervisible"),
		Fill:           s.String("newlayerfill"),
		Stroke:         s.String("newlayerstroke"),
		Opacity:        s.Float("newlayeropacity"),
		Published:      s.Bool("newlayerpublished"),
	}
}

func ResetLayerConfigSignals() map[string]any {
	return map[string]any{
		"newlayername":         "",
		"newlayerfile":         "",
		"newlayerpmtileslayer": "default",
		"newlayergeomtype":     "polygon",
		"newlayervisible":      true,
		"newlayerfill":         "#3388ff",
		"newlayerstroke":       "#2266cc",
		"newlayeropacity":      0.7,
		"newlayerpublished":    false,
	}
}
